baseurl = "https://brightonxx.github.io/"
title = "Brighton's Blog"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
preserveTaxonomyNames = true
hasCJKLanguage = true

[services]
  [services.googleAnalytics]
    id = "G-LQJH3PGC48"

[pagination]
pagerSize = 5

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
home = ["HTML", "RSS"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]
term = ["HTML", "RSS"]

[params]
  header_image = "img/home-bg.jpg"
  SEOTitle = "Brighton's Blog"
  description = "Welcome to my personal blog"
  keyword = "blog, personal website, technology, life"
  slogan = "Move Fast and Break Things"
  upstreamAttribution = false

  image_404 = "img/404-bg.jpg"
  title_404 = "Lost in the Digital Void"
  omit_categories = false

  # Sidebar settings
  sidebar_about_description = "Junior CS Student in SUSTech. Passionate about this world."
  sidebar_avatar = "img/avatar.png"

  featured_tags = true
  featured_condition_size = 1

  friends = false
  bookmarks = false
  about_me = true

  # Last posts
  last_posts = true

  # Giscus Comments (Visit https://giscus.app to get your configuration)
  # After configuration, uncomment and fill in the values below
  [params.giscus]
    repo = "BrightonXX/BrightonXX.github.io"           # Your GitHub repo
    # repoId = "R_kgDON..."                              # From Giscus setup
    # category = "Announcements"                          # Discussion category
    # categoryId = "DIC_kwDON..."                         # From Giscus setup
    mapping = "pathname"                                 # How comments are mapped
    theme = "light"                                     # Theme: light/dark/dim
    lang = "en"                                         # Language
    strict = "0"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "bottom"

  [params.social]
  rss = true
  email = "x2005jiay@gmail.com"
  # linkedin = ""  # Uncomment and add your LinkedIn if needed
  # stackoverflow = ""  # Uncomment and add your StackOverflow if needed
  github = "https://github.com/BrightonXX"

  [[params.additional_menus]]
  title = "TAGS"
  href = "/tags/"
  [[params.additional_menus]]
  title = "PROJECTS"
  href = "/projects/"
  [[params.additional_menus]]
  title = "ARCHIVE"
  href = "/archive/"
  [[params.additional_menus]]
  title = "ABOUT"
  href = "/about/"

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
