baseurl = "https://brightonxx.github.io/"
title = "Brighton's Blog"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
preserveTaxonomyNames = true
hasCJKLanguage = true

[pagination]
pagerSize = 5

[outputs]
home = ["HTML", "RSS"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]
term = ["HTML", "RSS"]

[params]
  header_image = "img/home-bg.jpg"
  SEOTitle = "Brighton's Blog"
  description = "Welcome to my personal blog"
  keyword = "blog, personal website, technology, life"
  slogan = "Move Fast and Break Things"
  upstreamAttribution = false

  image_404 = "img/404-bg.jpg"
  title_404 = "Lost in the Digital Void"
  omit_categories = false

  # Sidebar settings
  sidebar_about_description = "Junior CS Student in SUSTech. Passionate about this world."
  sidebar_avatar = "img/avatar.png"

  featured_tags = true
  featured_condition_size = 1

  friends = false
  bookmarks = false
  about_me = true

  # Last posts
  last_posts = true

  [params.social]
  rss = true
  email = "x2005jiay@gmail.com"
  # linkedin = ""  # Uncomment and add your LinkedIn if needed
  # stackoverflow = ""  # Uncomment and add your StackOverflow if needed
  github = "https://github.com/BrightonXX"

  [[params.additional_menus]]
  title = "POSTS"
  href = "/post/"
  [[params.additional_menus]]
  title = "TAGS"
  href = "/tags/"
  [[params.additional_menus]]
  title = "ARCHIVE"
  href = "/archive/"
  [[params.additional_menus]]
  title = "ABOUT"
  href = "/about/"

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
