baseurl = "https://brightonxx.github.io/"
title = "Brighton's Blog"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
preserveTaxonomyNames = true
hasCJKLanguage = true

[pagination]
pagerSize = 5

[outputs]
home = ["HTML", "RSS"]

[params]
  header_image = "img/home-bg-jeep.jpg"
  SEOTitle = "Brighton's Blog"
  description = "Welcome to my personal blog"
  keyword = "blog, personal website, technology, life"
  slogan = "Recording Life, Sharing Technology"
  upstreamAttribution = true

  image_404 = "img/404-bg.jpg"
  title_404 = "你来到了没有知识的荒原 :("
  omit_categories = false

  # Sidebar settings
  sidebar_about_description = "Software Developer, Open Source Enthusiast and Life Adventurer"
  sidebar_avatar = "img/avatar.png"

  featured_tags = true
  featured_condition_size = 1

  friends = true
  bookmarks = false
  about_me = true

  # Last posts
  last_posts = true

  [params.social]
  rss = true
  email = "youremail@gmail.com"
  linkedin = "https://www.linkedin.com/in/yourlinkedinid"
  stackoverflow = "https://stackoverflow.com/users/yourstackoverflowid"
  github = "https://github.com/BrightonXX"

  [[params.friend_link]]
  title = "Example Friend Link"
  href = "https://example.com"

  [[params.additional_menus]]
  title = "ARCHIVE"
  href = "/archive/"
  [[params.additional_menus]]
  title = "ABOUT"
  href = "/about/"

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
